name: dating_app
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  animated_bottom_navigation_bar: ^1.3.3
  card_swiper: ^3.0.1
  cloud_firestore: 4.15.3
  cupertino_icons: ^1.0.2
  dio: ^5.4.0
  firebase_auth: 4.17.3
  firebase_core: ^2.25.3
  flutter:
    sdk: flutter
  flutter_facebook_auth: ^6.0.4
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.3.10
  flutter_spinkit: ^5.2.0
  get: 4.6.6
  google_sign_in: 6.2.1
  sign_in_button: ^3.2.0

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/hearticon.png
    - assets/google.jpg
    - assets/facebook.png
    - assets/LikeButton.jpeg
    - assets/onboarding1.jpeg
    - assets/onboarding2.jpeg
    - assets/onboarding3.jpeg

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/hearticon.png"
  min_sdk_android: 21 # android min sdk min:16, default 21

flutter_native_splash:
  android: true
  ios: true
  background_image: "assets/background.jpg"
  image: "assets/hearticon.png"
  android_12:
    background_image: "assets/background.jpg"
    image: "assets/hearticon.png"
